// Generated by CoffeeScript 1.12.7
jQuery(document).ready(function($) {
  $('iframe[src*="youtube"]').each(function() {
    var div, h, iframe, p, w;
    iframe = $(this);
    div = $('<div />');
    div.insertBefore(iframe);
    iframe.detach().appendTo(div);
    p = 100;
    w = parseInt(iframe.attr('width'));
    h = parseInt(iframe.attr('height'));
    p = h / w;
    div.css({
      height: '0',
      paddingBottom: (p * 100.0) + "%",
      position: 'relative'
    });
    return iframe.css({
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      display: 'block'
    });
  });
  return $('.collapse-small-screens').each(function() {
    var div;
    div = $(this);
    return div.parent().addClass('row-collapse-small-screens');
  });
});
